- src/Blame.ts
- src/test/suite/Blame.test.ts
- src/test/suite/HeatMap.test.ts
* Fix name parsing
* Update tests accordingly
> Fix git blame name parsing

- src/Blame.ts
Fix git blame location issue and windows usage issue.
> Fix git blame location issues

- src/Blame.ts
- src/test/suite/Blame.test.ts
- src/test/suite/HeatMap.test.ts
Fix this issue https://github.com/JamiLu/simply-blame/issues/7
> Fix initial commit hash parsing

- package.json
Revise dark theme heat map color
> revise dark theme colors

- CHANGELOG.md
- src/Blame.ts
- src/BlameManager.ts
- src/ExtensionManager.ts
- src/HeatMap.ts
- src/HeatMapManager.ts
- src/Settings.ts
- src/Utils.ts
- src/test/suite/HeatMap.test.ts
* Fix uneven edge issue for unsymmetric fonts
* Improve color theme change, annotations change color as per theme changes
> Updates 009

- src/Blame.ts
- src/test/suite/Blame.test.ts
- src/test/suite/HeatMap.test.ts
git blame time zone may start with '-', this may fix #11
> fix time zone parse error

- package.json
- src/Date.ts
- src/test/suite/Date.test.ts
related issue: https://github.com/JamiLu/simply-blame/issues/26
> feature: support iso 8601 date format

- CHANGELOG.md
- package.json
- src/DecorationManager.ts
* Change blame annotation hover info box author icon
> Change info box author icon

- CHANGELOG.md
- package.json
- src/Blame.ts
Fix a parse blame information issue
> Fix parse blame info

- .github/workflows/run-tests.yml
Add merge group: types: checks_requested in run test action
> Add merge group

- CHANGELOG.md
- package.json
- src/Blame.ts
- src/BlameManager.ts
- src/Date.ts
* Improve date time parsing
* Improve blame width spacing
> Improve blame width spacing & date time parsing

- CHANGELOG.md
- package.json
* Update changelog
* Update version
> Prepare release 1.1.0

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/Blame.ts
- src/BlameManager.ts
- src/Date.ts
- src/Settings.ts
- src/test/suite/Blame.test.ts
- src/test/suite/Date.test.ts
- src/test/suite/HeatMap.test.ts
- src/test/suite/index.ts
* Implement configurable author style for blame annotations
* Fix blame parse issues and optimize blame parse.
> Implement configurable author style for blame annotations

- src/DecorationManager.ts
Fix author name not shown in the hover message.
> Fix hover annotation message

- package.json
Add descriptions for the heat color index strategy settings.
> Update heat color index strategy settings

- src/BlameManager.ts
- src/ExtensionManager.ts
Add a status bar item to tell when Simply Blame is busy loading and when loading completes.
> Add statusbar item

- README.md
add key features in the README
> add key features

- src/HashAction.ts
- src/Logger.ts
- src/extension.ts
The .git/config file is now looked up recursively in the workspace folders instead of assuming the folder being under the root folder.
> Fix .git/config not found issue

- src/Blame.ts
- src/BlameManager.ts
- src/Git.ts
- src/test/suite/Blame.test.ts
- src/test/suite/Git.test.ts
- src/test/suite/HeatMap.test.ts
Refactor blameFile function and command related functionalities into its own file that contains rest of the git and git command related code and update tests accordingly
> Refactor Blame.ts

- src/Command.ts
Changed the exec command to a spawn command which supports streaming. The exec command returned responses in one chunk which led to max buffer length exceeded error when the response was too big to fit in the buffer. The spawn command streams responses in chunks which prevents the buffer from exceeding the max size
> Fix max buffer length issue

- CHANGELOG.md
- src/Blame.ts
Fix parsing issues that caused blame annotations not show up for some files
> Fix & improve blame parsing
